### ISSUE TITLE
Как сдавать задачу 33?

### ISSUE THREAD

**Issue by MallabaevAzamat** [gsvgit/edu#97]
Возможно, есть шаблоны TeX для оформления документации(в особенности UML), или можно просто вставить скан?

**Comment by MallabaevAzamat** [comment]
А, можно я просто возьму, сформирую svg, и текст документации? если будет время запихну это в pdf

**Comment by gsvgit** [comment]
Особо шаблонов не встречал. По поводу UML есть такая вот штука:
https://www.draw.io/ умеет выгружать в pdf, который потом техом
замечательно вставляется в основной документ.  А можно и svg.

Regards,
Semyon Grigorev.

21 декабря 2015 г., 20:23 пользователь Mallabaev Azamat (Fenex9428) <
notifications@github.com> написал:

**Comment by MallabaevAzamat** [comment]
Спасибо
